---
- name: Run LEAPP pre-upgrade step
  hosts: '{{ _hosts | default(omit) }}'
  gather_facts: true
  become: true

  vars:
    leapp_upgrade_type: rhui
    report_server: '{{ _report_server | default(omit) }}'

  tasks:
    - name: Generate pre-upgrade analysis report
      ansible.builtin.import_role:
        name: infra.leapp.analysis

    - name: Create temp directory for reports
      ansible.builtin.tempfile:
        state: directory
      delegate_to: localhost
      register: _tempdir
      become: false

    - name: Create per-host report subdirectories
      ansible.builtin.file:
        path: '{{ _tempdir.path }}/{{ inventory_hostname }}'
        state: directory
        mode: 0755
      delegate_to: localhost
      become: false

    - name: Fetch LEAPP report artifacts locally
      ansible.builtin.fetch:
        src: '{{ item }}'
        dest: '{{ _tempdir.path }}/{{ inventory_hostname }}/'
        flat: true
      loop:
        - /var/log/ripu/ripu.log
        - /var/log/leapp/leapp-report.json
        - /var/log/leapp/leapp-report.txt
        - /var/log/leapp/leapp-preupgrade.log
        - /var/log/leapp/answerfile

    - name: Copy LEAPP report artifacts to report server
      ansible.builtin.copy:
        src: '{{ _tempdir.path }}/{{ inventory_hostname }}'
        dest: /var/www/html/leapp-reports
        mode: 0755
      delegate_to: '{{ report_server }}'
      when: report_server is defined

...
