---
- name: Run LEAPP pre-upgrade step
  hosts: '{{ _hosts | default(omit) }}'
  gather_facts: true
  become: true

  vars:
    leapp_upgrade_type: rhui
    report_server: '{{ _report_server | default(omit) }}'

  tasks:
    - name: Generate pre-upgrade analysis report
      tags: preupgrade
      ansible.builtin.import_role:
        name: infra.leapp.analysis

    - name: Sync LEAPP report to report server
      tags: sync-reports
      ansible.posix.synchronize:
        src: /var/log/leapp
        dest: /var/www/html/leapp-reports/{{ inventory_hostname }}
        mode: pull
        use_ssh_args: true
      delegate_to: '{{ report_server }}'
      when: report_server is defined
      vars:
        ansible_ssh_extra_args: '-o ForwardAgent=yes'

...
